yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    ),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "app_posts"

urlpatterns = [
    path(
        "",
        views.index,
        name="index"
    ),
    path(
        "group/<slug:slug>/",
        views.group_posts,
        name="group_list"
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        "profile/<str:username>/",
        views.profile,
        name="profile"
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name="add_comment"
    ),
    path(
        "posts/<int:post_id>/edit/",
        views.post_edit,
        name="post_edit"
    ),
    path(
        "posts/<int:post_id>/",
        views.post_detail,
        name="post_detail"
    ),
    path(
        "create/",
        views.post_create,
        name="post_create"
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(
        '',
        include(
            'posts.urls',
            namespace='app_posts'
        )
    ),
    path(
        'admin/',
        admin.site.urls
    ),
    path(
        'auth/',
        include(
            'users.urls',
            namespace='users'
        )
    ),
    path(
        'auth/',
        include(
            'django.contrib.auth.urls'
        )
    ),
    path(
        'about/',
        include(
            'about.urls',
            namespace='about'
        )
    ),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models

User = get_user_model()


class Group(
    models.Model
):
    title = models.CharField(
        max_length=200
    )
    slug = models.SlugField(
        max_length=200,
        unique=True
    )
    description = models.TextField()

    def __str__(
        self
    ):
        return self.slug


class Post(
    models.Model
):
    text = models.TextField(
        validators=[
            MinLengthValidator(
                limit_value=15,
                message="Длина этого поля должна быть не менее 15 символов"
            )
        ]
    )
    pub_date = models.DateTimeField(
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = [
            '-pub_date'
        ]

    def __str__(
        self
    ):
        return self.text


class Comment(
    models.Model
):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = [
            '-created'
        ]

    def __str__(
        self
    ):
        return self.text


class Follow(
    models.Model
):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    def __str__(
        self
    ):
        return self.user.username

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(
    forms.ModelForm
):

    class Meta:
        model = Post
        fields = (
            "text",
            "group",
            "image",
        )


class CommentForm(
    forms.ModelForm
):

    class Meta:
        model = Comment
        fields = (
            'text',
        )

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Group, Post, User


def index(
    request
):
    post_list = Post.objects.select_related(
        'group'
    ).all()
    paginator = Paginator(
        post_list,
        settings.NAMBER_OF_POSTS
    )
    page_number = request.GET.get(
        "page"
    )
    page_obj = paginator.get_page(
        page_number
    )
    template = "posts/index.html"
    context = {
        "page_obj": page_obj,
    }
    return render(
        request,
        template,
        context
    )


def group_posts(
    request,
    slug
):
    template = "posts/group_list.html"
    group = get_object_or_404(
        Group,
        slug=slug
    )
    post_list = group.posts.order_by(
        "-pub_date"
    )
    paginator = Paginator(
        post_list,
        settings.NAMBER_OF_POSTS
    )
    page_number = request.GET.get(
        "page"
    )
    page_obj = paginator.get_page(
        page_number
    )
    context = {
        "group": group,
        "page_obj": page_obj,
    }
    return render(
        request,
        template,
        context
    )


def profile(
    request,
    username
):
    author = get_object_or_404(
        User,
        username=username
    )
    post_list = Post.objects.filter(
        author=author.id
    ).order_by(
        "-pub_date"
    )
    paginator = Paginator(
        post_list,
        settings.NAMBER_OF_POSTS
    )
    page_number = request.GET.get(
        "page"
    )
    page_obj = paginator.get_page(
        page_number
    )
    template = "posts/profile.html"
    count = post_list.count()

    following = False
    if request.user.is_authenticated:
        following = author.following.filter(
            user=request.user
        )
    context = {
        "post_list": post_list,
        "author": author,
        "page_obj": page_obj,
        "count": count,
        "following": following,
    }
    return render(
        request,
        template,
        context
    )


def post_detail(
    request,
    post_id
):
    one_post = get_object_or_404(
        Post,
        pk=post_id
    )
    post_list = Post.objects.all()
    count = one_post.author.posts.count()
    form = CommentForm(
        request.POST or None
    )
    comments = one_post.comments.all()
    template = "posts/post_detail.html"
    context = {
        'one_post': one_post,
        'post_list': post_list,
        'count': count,
        'form': form,
        'comments': comments,
    }
    return render(
        request,
        template,
        context
    )


@login_required
def post_create(
    request
):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )

    if form.is_valid():
        post = form.save(
            commit=False
        )
        post.author = request.user
        post.save()
        return redirect(
            "app_posts:profile",
            username=post.author
        )
    return render(
        request,
        "posts/create_post.html",
        {
            "form": form
        }
    )


@login_required
def post_edit(
    request,
    post_id
):
    post = get_object_or_404(
        Post,
        pk=post_id
    )
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if post.author == request.user:
        if form.is_valid():
            form.save()
            return redirect(
                "app_posts:post_detail",
                post_id
            )
        context = {
            'form': form,
            'is_edit': True,
            'post': post
        }
        return render(
            request,
            "posts/create_post.html",
            context
        )
    return redirect(
        "app_posts:post_detail",
        post_id
    )


@login_required
def add_comment(
    request,
    post_id
):
    post = get_object_or_404(
        Post,
        pk=post_id,
    )
    form = CommentForm(
        request.POST or None
    )
    if form.is_valid():
        comment = form.save(
            commit=False
        )
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect(
        'app_posts:post_detail',
        post_id=post_id
    )


@login_required
def follow_index(
    request
):
    post_list = Post.objects.filter(
        author__following__user=request.user
    ).select_related(
        'group',
        'author'
    )
    paginator = Paginator(
        post_list,
        settings.NAMBER_OF_POSTS
    )
    page_number = request.GET.get(
        "page"
    )
    page_obj = paginator.get_page(
        page_number
    )
    context = {
        "page_obj": page_obj,
    }
    return render(
        request,
        'posts/follow.html',
        context
    )


@login_required
def profile_follow(
    request,
    username
):
    author = get_object_or_404(
        User,
        username=username
    )
    if request.user != author:
        request.user.follower.get_or_create(
            user=request.user,
            author=author
        )
    return redirect(
        'app_posts:profile',
        username
    )


@login_required
def profile_unfollow(
    request,
    username
):
    author = get_object_or_404(
        User,
        username=username
    )
    follow_obj = author.following.filter(
        user=request.user,
        author=author
    )
    if follow_obj.exists():
        follow_obj.delete()

    return redirect(
        'app_posts:profile',
        username
    )

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  <title>
    {% if is_edit %}
      Редактировать запись
    {% else %}
      Добавить запись
    {% endif %}
  </title>
{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}             
              </div>
              <div class="card-body">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
                {% endfor %}
                {% endif %}        
                <form method="post" enctype="multipart/form-data" action="{% url 'app_posts:post_create' %}">
                  {% csrf_token %}            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text }}               
                    <small class="helptext text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    {{ form.group }}
                    <span class="helptext text-muted">
                      Группа, к которой будет относиться пост
                    </span>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка
                    </label>
                    <input type='file' name='image' accept='image/' class='form-control' id='id_image'>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <title>Последние обновления в избранном</title>
{% endblock %}
{% block content %}
  <main> 
    <div class="container py-5">     
      <h1>Последние обновления в избранном</h1>
      {% include 'includes/switcher.html' %}
      <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор:
              {% if post.author.get_full_name %}
              {{ post.author.get_full_name }}
              {% else %}
              {{ post.author }}
              {% endif %}
              <a href="{% url "app_posts:profile" post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          {% if post.group != None %}
            <a href="{% url "app_posts:post_detail" post.pk %}">подробная информация</a>
            <br>   
            <a href="{% url "app_posts:group_list" post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}      
      </article>
    </div>  
  </main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  <title> 
    Записи сообщества 
    {% for group in page_obj %}
    {% if forloop.last %}
    {{ group.group.title }}
    {% endif %}
    {% endfor %}
  </title>
{% endblock %}
{% block content %}
  <main>
    <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5">
      {% for group in page_obj %}
      {% if forloop.last %}
      <h1>{{ group.group }}</h1>
      <p>{{ group.group.description }}</p>
      {% endif %}
      {% endfor %}
      <article>
        {% for group in page_obj %}
          <ul>
            <li>
              Автор:
              {% if group.author.get_full_name %}
              {{ group.author.get_full_name }}
              {% else %}
              {{ group.author }}
              {% endif %}
            </li>
            <li>
              Дата публикации: {{ group.pub_date|date:"d E Y" }}
            </li>
          </ul> 
          {% thumbnail group.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ group.text }}</p>
        {% endfor %}
        {% include 'includes/paginator.html' %}
      </article>
      <!-- под последним постом нет линии -->
    </div>  
  </main>
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <title>Последние обновления на сайте</title>
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">     
      <h1>Последние обновления на сайте</h1>
      {% include 'includes/switcher.html' %}
      <article>
        {% load cache %}
        {% cache 20 index_page %}
        {% for post in page_obj %}
          <ul>
            <li>
              Автор:
              {% if post.author.get_full_name %}
              {{ post.author.get_full_name }}
              {% else %}
              {{ post.author }}
              {% endif %}
              <a href="{% url "app_posts:profile" post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          {% if post.group != None %}
            <a href="{% url "app_posts:post_detail" post.pk %}">подробная информация</a>
            <br>   
            <a href="{% url "app_posts:group_list" post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% endcache %}
        {% include 'includes/paginator.html' %}      
      </article>
    </div>  
  </main>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}
  <title>  
    {% for post in post_list %}
    {% if forloop.last %}
    {{ post.text|truncatechars:30 }}
    {% endif %}
    {% endfor %}
  </title>
{% endblock %}
{% block content %}
<main>
  <div class="row">
    <aside class="col-12 col-md-3">
      {% for post in post_list %}
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>  
          <li class="list-group-item">
            {% if post.group %}
            Группа:
            {{ post.group.slug }}
            <a href="{% url "app_posts:group_list" post.group.slug %}">
              все записи группы
            </a>
            {% else %}
            У этого поста нет группы
            {% endif %}
          </li>
          <li class="list-group-item">
            Автор: 
            {% if post.author.get_full_name %}
            {{ post.author.get_full_name }}
            {% else %}
            {{ post.author }}
            {% endif %}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url "app_posts:profile" post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {% for post in form %}
        {% endfor %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {{ post.text }}
        <br>
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url "app_posts:post_edit" post.pk %}">
          редактировать запись
        </a>
        {% endif %}
        {% endfor %}
        {% if user.is_authenticated %}
        <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'app_posts:add_comment' one_post.pk %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
          {% endif %} 
          {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'app_posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                 {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %}
        </div>
      </p>
    </article>
  </div> 
</main>
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <title>{{ title }}</title>
{% endblock %}
{% block content %}
<main>
  <div class="container py-5">        
    <h1>Все посты пользователя
      {% for post in page_obj %}
      {% if forloop.last %} 
      {% if post.author.get_full_name %}
      {{ post.author.get_full_name }}
      {% else %}
      {{ post.author }}
      {% endif %}
      {% endif %} 
      {% endfor %}
    </h1>
    <h3>Всего постов: {{ count }} </h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'app_posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'app_posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %} 
    <article>
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url "app_posts:profile" post.author %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
      </ul>
      <p>
      {{ post.text }}
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      </p>
      <a href="{% url "app_posts:post_detail" post.pk %}">подробная информация</a>
    </article>
    <br>
    {% if post.group %}       
    <a href="{% url "app_posts:group_list" post.group.slug %}">все записи группы</a> 
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}       
    {% endfor %}
    {% include 'includes/paginator.html' %}  
  </div>
</main>
{% endblock %}